services:
  postgres:
    image: postgres:16
    container_name: dme_db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - dme_data:/var/lib/postgresql/data
    networks:
      - app-network
    logging:
      options:
        max-size: "10m"
        max-file: "2"

  migrate:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - postgres
    command: >
      sh -c "npx prisma db push"
    networks:
      - app-network
  fetch:
    container_name: dme_fetch
    restart: on-failure
    env_file:
      - .env
    build:
      context: .
      dockerfile: packages/fetch/Dockerfile
    depends_on:
      - migrate
    networks:
      - app-network

  api:
    container_name: api
    restart: on-failure
    env_file:
      - .env
    build:
      context: .
      dockerfile: packages/api/Dockerfile
    ports:
      - "3030:3030"
    depends_on:
      - migrate
    networks:
      - app-network
    logging:
      options:
        max-size: "25m"
        max-file: "2"

networks:
  app-network:
    driver: bridge

volumes:
  dme_data: